#server:
#  port: 2001
  
spring:
  application:
    name: eureka

    
eureka:
  server:
    enable-self-preservation: false   # 是否开启自我保护
  client:
    register-with-eureka: false       # 是否向自身注册
    fetch-registry: false             # 是否从自身拉取注册信息
  instance: 
    lease-expiration-duration-in-seconds: 90  # 最后一次心跳后多久没有接收到心跳认为服务不可用  
#  instance:
#    hostname: eureka1
#  client:
#    register-with-eureka: false
#    fetch-registry: false

---
spring:
  profiles: eureka1

server:
  port: 2001
  
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:2002/eureka
---
spring:
  profiles: eureka2

server:
  port: 2002
  
eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka     
      
      